import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>NovaCare Hospital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
	  <div>
      <section className="banner">
          <div className="container">
            <div className="row">
              <div className="col-lg-6 col-md-12 col-xl-7">
                <div className="block">
                  <div className="divider mb-3"></div>
                  <span className="text-uppercase text-sm letter-spacing ">Total Health care solution</span>
                  <h1 className="mb-3 mt-3">Your most trusted health partner</h1>

                  <p className="mb-4 pr-5">A repudiandae ipsam labore ipsa voluptatum quidem quae laudantium quisquam aperiam maiores sunt fugit, deserunt rem suscipit placeat.</p>
                  <div className="btn-container ">
                    <Link href="/appointment" className="btn btn-main-2 btn-icon btn-round-full">Make appointment <i className="icofont-simple-right ml-2  "></i></Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
    </div>

      <section className="features">
	<div className="container">
		<div className="row">
			<div className="col-lg-12">
				<div className="feature-block d-lg-flex">
					<div className="feature-item mb-5 mb-lg-0">
						<div className="feature-icon mb-4">
							<i className="icofont-surgeon-alt"></i>
						</div>
						<span>24 Hours Service</span>
						<h4 className="mb-3">Online Appoinment</h4>
						<p className="mb-4">Get ALl time support for emergency.We have introduced the principle of family medicine.</p>
						<a href="/appoinment" className="btn btn-main btn-round-full">Make a appoinment</a>
					</div>
				
					<div className="feature-item mb-5 mb-lg-0">
						<div className="feature-icon mb-4">
							<i className="icofont-ui-clock"></i>
						</div>
						<span>Timing schedule</span>
						<h4 className="mb-3">Working Hours</h4>
						<ul className="w-hours list-unstyled">
							<li className="d-flex justify-content-between">Sun - Wed : <span>8:00 - 17:00</span></li>
							<li className="d-flex justify-content-between">Thu - Fri : <span>9:00 - 17:00</span></li>
							<li className="d-flex justify-content-between">Sat - sun : <span>10:00 - 17:00</span></li>
						</ul>
					</div>
				
					<div className="feature-item mb-5 mb-lg-0">
						<div className="feature-icon mb-4">
							<i className="icofont-support"></i>
						</div>
						<span>Emegency Cases</span>
						<h4 className="mb-3">1-800-700-6200</h4>
						<p>Get ALl time support for emergency.We have introduced the principle of family medicine.Get Conneted with us for any urgency .</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section className="section about">
	<div className="container">
		<div className="row align-items-center">
			<div className="col-lg-4 col-sm-6">
				<div className="about-img">
					<img src="images/about/img-1.jpg" alt="" className="img-fluid"/>
					<img src="images/about/img-2.jpg" alt="" className="img-fluid mt-4"/>
				</div>
			</div>
			<div className="col-lg-4 col-sm-6">
				<div className="about-img mt-4 mt-lg-0">
					<img src="images/about/img-3.jpg" alt="" className="img-fluid"/>
				</div>
			</div>
			<div className="col-lg-4">
				<div className="about-content pl-4 mt-4 mt-lg-0">
					<h2 className="title-color">Personal care <br/>& healthy living</h2>
					<p className="mt-4 mb-5">We provide best leading medicle service Nulla perferendis veniam deleniti ipsum officia dolores repellat laudantium obcaecati neque.</p>

					<a href="service.html" className="btn btn-main-2 btn-round-full btn-icon">Services<i className="icofont-simple-right ml-3"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>
      </main>
    </>
  )
}
